language: java
matrix:
  include:
  - env:
    - TUM='TUM.jar'
    os: linux
    dist: xenial
    sudo: required
install:
- sudo apt-get install ant
before_install:
- openssl aes-256-cbc -K $encrypted_1b927e5de713_key -iv $encrypted_1b927e5de713_iv
  -in tum-key.enc -out tum-key -d
- sudo apt-get install git-crypt
script:
- git-crypt unlock tum-key
- ant create_run_jar
before_deploy:
- java -jar TUM.jar selfencrypt
deploy:
  provider: releases
  name: "${TRAVIS_COMMIT_MESSAGE}"
  api_key:
    secure: jPOgNpHTGfa7SSyOXO21/qWY6HhKagaZ4XF3OHRG7fovWWch5NycJ+7FIQv8HkuLQ1/fAl57DVMoTTmpouswOAomvYu9lW8ez5Bavyb8HVfWdtJ9hVnPJ/x7HYjol44zT9zs/bCSH3d25IbNotTknTgg2P8fPAlBrzjOezwgOybq1tui8uNRNzcV1RRpVEypL5zwQO6fDhQVDV99pVeY4Gm33AToTMXqahi4eEolqDdTNcEzlkXJPZB6FH0LkPL6W1XH3ubCXD1i5/O7zEBRuxTcfSRbXoePDzacEa0zhwHripF8ojOKdfKoUhV17/7ol4CHVbT63oa6S17j4y0Ufk3txzjL2HNEEE7Iegb3/RC4MJPQLdlXCeDCyHlOTmEo+ZXwZpsN46LpO+mzL/dPznA+cr0DpVI0XZhkXjiFoPmAwZwU/caodDIsKk9ffnhN7CprzZu7DX3RH1cyL8mCaLPLxd4gue7mO1R5BEIYePwdnjDiYXNbj1MepWFU7ione5CybcWWarbT8Gn4PMwduI65PmmlmASNuu1oZ638wK36m1LiUdASUR70uSqiqR+LGwagAoO4NdcOdUFh814pKrU0fepfm3zJ+7ULWivsBftU6pU/qVdNdW0zZXugVKBDPLJfCU0voogyjUhR73vY07qyMYI3PaSp9SfrD4u/dX4=
  file: TUM-enc.jar
  skip_cleanup: true
  on:
    tags: true
