language: java
matrix:
  include:
  - env:
    - TUM='TUM.jar'
    os: linux
    dist: xenial 
    sudo: required

install: 
- sudo apt-get install ant

before_install:
- openssl aes-256-cbc -K $encrypted_1b927e5de713_key -iv $encrypted_1b927e5de713_iv
  -in tum-key.enc -out tum-key -d
- sudo apt-get install git-crypt

script:
- git-crypt unlock tum-key
- ant build

